# Generated by Django 2.1.3 on 2019-03-02 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeoLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MediaAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('disaster_type', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(blank=True)),
                ('location_name', models.CharField(blank=True, max_length=255)),
                ('disaster_severity', models.CharField(blank=True, max_length=255)),
                ('tags', models.TextField(blank=True)),
                ('geo_location', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geo_location', to='api.GeoLocation')),
            ],
        ),
    ]
