# Generated by Django 2.1.3 on 2019-03-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaalert',
            name='country',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
